const assert = require('node:assert/strict');
const fs = require('node:fs');
let playwright;
try { playwright = require('playwright'); } catch { playwright = require(`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`); }
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5000';
(async () => {
  const browser = await playwright.chromium.launch({ headless: true });
  let checks = 0;
  const check = (actual, expected, label) => { assert.deepEqual(actual, expected, label); checks++; };
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const request = await playwright.request.newContext({ baseURL: base });
  try {
    await page.goto(base);
    await page.locator('.recipe-card').first().waitFor();
    check(await page.locator('.recipe-card').count(), 8, 'Seeded recipes render');
    await page.getByRole('button', { name: 'Open Spaghetti Bolognese', exact: true }).click();
    const modal = page.getByRole('dialog');
    check(await modal.getByRole('heading', { name: 'Spaghetti Bolognese' }).isVisible(), true, 'Detail view');
    await page.getByRole('button', { name: 'Increase servings' }).click();
    check(await page.getByTestId('servings').textContent(), '5 servings', 'Serving adjustment');
    check(await page.getByTestId('ingredient-quantity').first().textContent(), '500 g', 'Ingredients scale');
    await page.getByRole('button', { name: 'Mark step 1 complete' }).click();
    check(await page.getByRole('button', { name: 'Mark step 1 incomplete' }).getAttribute('aria-pressed'), 'true', 'Cooking checklist');
    await page.getByLabel('Kitchen notes', { exact: true }).fill('More garlic next time.');
    await page.getByLabel('My rating', { exact: true }).selectOption('5');
    await page.getByRole('button', { name: 'Save notes & rating', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Your kitchen notes are saved.');
    await page.getByRole('button', { name: 'I cooked this today', exact: true }).click();
    await page.getByTestId('cooking-history').filter({ hasText: 'Made 1 time' }).waitFor();
    checks++;
    await page.getByLabel('Timer minutes').fill('1');
    await page.getByRole('button', { name: 'Start timer', exact: true }).click();
    await page.getByRole('button', { name: 'Pause timer', exact: true }).click();
    check(await page.getByRole('button', { name: 'Resume timer', exact: true }).isVisible(), true, 'Timer pauses');
    await page.getByRole('button', { name: 'Reset timer', exact: true }).click();
    check(await page.getByLabel('Time remaining').textContent(), '00:00', 'Timer resets');
    const recipeDownloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download recipe', exact: true }).click();
    const recipeDownload = await recipeDownloadPromise;
    const recipeText = fs.readFileSync(await recipeDownload.path(), 'utf8');
    check(recipeText.includes('500 g spaghetti') && recipeText.includes('More garlic next time.'), true, 'Download uses selected servings and personal notes');
    await page.getByRole('button', { name: '♡ Save recipe', exact: true }).click();
    await page.getByRole('button', { name: '♥ Saved', exact: true }).waitFor();
    checks++;
    await page.keyboard.press('Escape');
    await page.getByRole('dialog').waitFor({ state: 'detached' });
    checks++;
    await page.getByRole('button', { name: 'Saved recipes', exact: true }).click();
    check(await page.locator('.recipe-card').count(), 3, 'Saved recipes');
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('coconut milk');
    check(await page.locator('.recipe-card').count(), 1, 'Ingredient search');
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('unfindable');
    check(await page.getByText('No recipes on this shelf.').isVisible(), true, 'Empty search');
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('');
    await page.getByRole('button', { name: 'Desserts', exact: true }).click();
    check(await page.locator('.recipe-card').count(), 1, 'Category filter');
    await page.getByRole('button', { name: 'All recipes', exact: true }).click();
    await page.getByRole('button', { name: '＋ Add recipe', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).fill('Browser test rice');
    await page.getByLabel('What makes it special?').fill('A test recipe for an actual weekly shopping list.');
    await page.getByLabel('Minutes', { exact: true }).fill('15');
    await page.getByLabel('Servings', { exact: true }).fill('2');
    await page.getByLabel('Ingredient 1 name').fill('rice');
    await page.getByLabel('Ingredient 1 quantity').fill('100');
    await page.getByLabel('Step 1', { exact: true }).fill('Cook the rice according to the packet.');
    await page.getByRole('button', { name: 'Add to my cookbook ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'Browser test rice', exact: true }).waitFor();
    checks++;
    await page.getByRole('button', { name: 'Edit recipe', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).fill('Everyday rice');
    await page.getByRole('button', { name: 'Save changes ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'Everyday rice', exact: true }).waitFor();
    checks++;
    await page.getByRole('button', { name: 'Increase servings' }).click();
    const day = await page.locator('#plan-day').inputValue();
    await page.getByRole('button', { name: 'Add to meal plan ↗', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Dinner is on the menu.');
    checks++;
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
    const slot = page.locator(`[id="${day}-Dinner"]`);
    check(await slot.locator('option:checked').textContent(), 'Everyday rice', 'Meal appears on selected day');
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.locator('.shopping-item').first().waitFor();
    check(await page.locator('.shopping-item').count(), 1, 'Shopping list generated');
    check(await page.locator('.shopping-item').textContent(), 'rice150 g', 'Shopping quantities use planned servings');
    await page.locator('.shopping-item input').check();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'One less thing to pick up.');
    await page.reload();
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.locator('.shopping-item').first().waitFor();
    check(await page.locator('.shopping-item input').isChecked(), true, 'Shopping checks persist');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download my list ↓', exact: true }).click();
    const download = await downloadPromise;
    check(download.suggestedFilename().startsWith('shopping-'), true, 'Shopping list export');
    const path = await download.path();
    check(fs.readFileSync(path, 'utf8').includes('[x] rice: 150 g'), true, 'Export contains real list data');
    await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
    await page.getByRole('button', { name: 'Next week', exact: true }).click();
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.getByText('Your basket starts with a plan.').waitFor();
    checks++;
    await page.getByRole('button', { name: 'This week', exact: true }).click();
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Open Everyday rice', exact: true }).click();
    await page.getByRole('button', { name: 'Delete recipe', exact: true }).click();
    await page.getByRole('button', { name: 'Keep it', exact: true }).click();
    check(await modal.isVisible(), true, 'Delete cancellation');
    await page.getByRole('button', { name: 'Delete recipe', exact: true }).click();
    await page.getByRole('button', { name: 'Yes, delete recipe', exact: true }).click();
    await modal.waitFor({ state: 'detached' });
    check(await page.locator('.recipe-card').count(), 8, 'Delete recipe');
    const plan = await (await request.get('/api/plan')).json();
    check(plan, [], 'Deletion removes planned meals');
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Unsave Spaghetti Bolognese', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Recipe removed from saved.');
    fs.mkdirSync('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/cookbook-desktop.png', fullPage: true });
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Cookbook fits ${width}px`);
      if (width === 390) await page.screenshot({ path: 'test-results/cookbook-mobile.png', fullPage: true });
      await page.getByRole('button', { name: 'Open Spaghetti Bolognese', exact: true }).click();
      check(await modal.evaluate(el => el.scrollWidth <= el.clientWidth), true, `Recipe detail fits ${width}px`);
      await page.keyboard.press('Escape');
      await modal.waitFor({ state: 'detached' });
      await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Meal plan fits ${width}px`);
      await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    }
    await page.locator('.recipe-card').last().scrollIntoViewIfNeeded();
    await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
    checks++;
    await page.getByLabel('30 minutes or less', { exact: true }).check();
    const recipeData = await (await request.get('/api/recipes')).json();
    check(await page.locator('.recipe-card').count(), recipeData.filter(r => r.time <= 30).length, 'Quick meals filter');
    await page.getByLabel('30 minutes or less', { exact: true }).uncheck();
    await page.getByRole('button', { name: 'Open Spaghetti Bolognese', exact: true }).click();
    check(await page.getByLabel('Kitchen notes').inputValue(), 'More garlic next time.', 'Notes persist after reload');
    check(await page.getByLabel('My rating').inputValue(), '5', 'Rating persists after reload');
    check(await page.getByTestId('cooking-history').textContent().then(t => t.includes('Made 1 time')), true, 'Cooking history persists');
    const exportPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export recipe file', exact: true }).click();
    const exported = JSON.parse(fs.readFileSync(await (await exportPromise).path(), 'utf8'));
    check(exported.recipes[0].servings, 4, 'Portable recipe retains original serving size');
    check(exported.recipes[0].journal, undefined, 'Portable recipe excludes personal notes');
    await page.getByRole('button', { name: 'Make my own version', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).waitFor();
    check(await page.getByLabel('Recipe name', { exact: true }).inputValue(), 'Spaghetti Bolognese (my version)', 'Duplicate opens editable copy');
    await page.getByLabel('Recipe name', { exact: true }).fill('My garlic pasta');
    await page.getByRole('button', { name: 'Save changes ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'My garlic pasta', exact: true }).waitFor();
    check(await page.getByLabel('Kitchen notes').inputValue(), '', 'Copy starts with a clean notebook');
    await page.keyboard.press('Escape');
    await modal.waitFor({ state: 'detached' });
    await page.getByRole('button', { name: 'Import recipes', exact: true }).click();
    await page.getByLabel('Choose recipe file', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{broken') });
    await modal.getByRole('alert').waitFor();
    check(await page.getByRole('button', { name: 'Add these recipes', exact: true }).count(), 0, 'Malformed import cannot be saved');
    exported.recipes[0].title = 'Imported pasta';
    await page.getByLabel('Choose recipe file', { exact: true }).setInputFiles({ name: 'recipes.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
    await modal.getByRole('heading', { name: '1 recipe ready to add', exact: true }).waitFor();
    check((await (await request.get('/api/recipes')).json()).length, 9, 'Import preview does not write data');
    await page.getByRole('button', { name: 'Add these recipes', exact: true }).click();
    await modal.waitFor({ state: 'detached' });
    check(await page.locator('.recipe-card').count(), 10, 'Import adds recipes without replacing existing cookbook');
    const extras = (await (await request.get('/api/recipes')).json()).filter(r => ['My garlic pasta', 'Imported pasta'].includes(r.title));
    for (const r of extras) await request.delete(`/api/recipes/${r.id}`);
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    const foundMeal = { idMeal: '52771', strMeal: 'Discovery test rice', strCategory: 'Vegetarian', strArea: 'Kenyan', strInstructions: 'Cook the rice.\\nServe warm.', strMealThumb: 'https://www.themealdb.com/images/media/meals/discovery-test.jpg', strIngredient1: 'rice', strMeasure1: '1/2 cup', strIngredient2: 'salt', strMeasure2: 'pinch' };
    await page.route('https://www.themealdb.com/images/media/meals/discovery-test.jpg', route => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900"><rect width="900" height="900" fill="green"/></svg>' }));
    await page.route('**/api/discover**', route => {
      const url = new URL(route.request().url());
      if (url.searchParams.get('q') === 'offline') return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'TheMealDB is unavailable right now.' }) });
      const data = url.pathname.endsWith('/52771') ? foundMeal : url.searchParams.get('q') === 'missing' ? [] : [foundMeal];
      return route.fulfill({ contentType: 'application/json', body: JSON.stringify(data) });
    });
    await page.getByRole('button', { name: 'Find recipes', exact: true }).click();
    await page.getByLabel('Recipe source', { exact: true }).selectOption('mealdb');
    await page.getByLabel('Search by dish name').fill('missing');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('heading', { name: 'No dishes found.', exact: true }).waitFor();
    checks++;
    await page.getByLabel('Search by dish name').fill('offline');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'TheMealDB is unavailable' }).waitFor();
    checks++;
    await page.getByLabel('Search by dish name').fill('rice');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Review Discovery test rice', exact: true }).waitFor();
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Recipe discovery fits ${width}px`);
    }
    await page.getByRole('button', { name: 'Review Discovery test rice', exact: true }).click();
    await page.getByRole('dialog', { name: 'Review imported recipe', exact: true }).waitFor();
    check(await page.getByLabel('Minutes', { exact: true }).inputValue(), '', 'Unknown cooking time needs review');
    check(await page.getByLabel('Servings', { exact: true }).inputValue(), '', 'Unknown serving count needs review');
    check(await page.getByLabel('Ingredient 1 quantity').inputValue(), '0.5', 'Fractional measurement is converted');
    check(await page.getByLabel('Ingredient 2 quantity').inputValue(), '', 'Pinch is not converted to a guessed quantity');
    check((await (await request.get('/api/recipes')).json()).length, 8, 'Review does not add a recipe');
    await page.getByLabel('Minutes', { exact: true }).fill('20');
    await page.getByLabel('Servings', { exact: true }).fill('4');
    await page.getByLabel('Ingredient 2 quantity').fill('0.25');
    await page.getByLabel('Ingredient 2 unit').selectOption('tsp');
    await page.screenshot({ path: 'test-results/import-review.png', fullPage: true });
    await page.getByRole('button', { name: 'Add to my cookbook ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'Discovery test rice', exact: true }).waitFor();
    check(await modal.getByRole('link', { name: 'TheMealDB — view original', exact: true }).getAttribute('href'), 'https://www.themealdb.com/meal/52771', 'Attribution saved with recipe');
    check(await modal.locator('.detail-top>img').getAttribute('src'), foundMeal.strMealThumb, 'Recipe uses actual meal photo');
    await page.getByRole('button', { name: 'Decrease servings', exact: true }).click();
    await page.getByRole('button', { name: 'Decrease servings', exact: true }).click();
    const importedDay = await page.locator('#plan-day').inputValue();
    await page.getByRole('button', { name: 'Add to meal plan ↗', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Dinner is on the menu.');
    const importedItems = await (await request.get(`/api/shopping?start=${importedDay}&end=${importedDay}`)).json();
    check(importedItems.find(item => item.name === 'rice').quantity, 0.25, 'Discovered recipe scales into shopping list');
    const importedRecipe = (await (await request.get('/api/recipes')).json()).find(r => r.title === foundMeal.strMeal);
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Open Discovery test rice', exact: true }).click();
    check(await modal.getByRole('link', { name: 'TheMealDB — view original', exact: true }).isVisible(), true, 'Imported source persists after reload');
    await page.keyboard.press('Escape');
    await modal.waitFor({ state: 'detached' });
    await request.delete(`/api/recipes/${importedRecipe.id}`);
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Find recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Surprise me', exact: true }).click();
    await page.getByRole('button', { name: 'Review Discovery test rice', exact: true }).waitFor();
    checks++;
    await page.screenshot({ path: 'test-results/discover-desktop.png', fullPage: true });
    await page.unroute('**/api/discover**');
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();

    const wikiPage = { page_id: '654321', revision: '987654', title: 'Wikibooks test rice', ingredients: ['2 cups rice', 'Salt to taste'], instructions: ['Cook rice.', 'Serve warm.'] };
    await page.route('**/api/discover**', route => {
      const url = new URL(route.request().url());
      if (url.pathname.endsWith('/wikibooks/654321')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify(wikiPage) });
      if (url.pathname.endsWith('/wikibooks')) {
        if (url.searchParams.get('q') === 'partial') return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Wikibooks offline.' }) });
        return route.fulfill({ contentType: 'application/json', body: JSON.stringify([{ page_id: '654321', title: wikiPage.title }]) });
      }
      return route.fulfill({ contentType: 'application/json', body: JSON.stringify([foundMeal]) });
    });
    await page.getByRole('button', { name: 'Find recipes', exact: true }).click();
    await page.getByLabel('Recipe source', { exact: true }).selectOption('all');
    await page.getByLabel('Search by dish name').fill('rice');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Review Wikibooks test rice', exact: true }).waitFor();
    check(await page.locator('.discover-page .recipe-card').count(), 2, 'Combined search includes both providers');
    await page.getByLabel('Search by dish name').fill('partial');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Wikibooks offline.' }).waitFor();
    check(await page.getByRole('button', { name: 'Review Discovery test rice', exact: true }).isVisible(), true, 'Partial provider outage preserves available results');
    await page.getByLabel('Recipe source', { exact: true }).selectOption('wikibooks');
    await page.getByLabel('Search by dish name').fill('rice');
    await page.getByRole('button', { name: 'Search recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Review Wikibooks test rice', exact: true }).waitFor();
    check(await page.locator('.discover-page .recipe-card').count(), 1, 'Source selector searches only Wikibooks');
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Combined recipe search fits ${width}px`);
    }
    await page.screenshot({ path: 'test-results/wikibooks-search.png', fullPage: true });
    await page.getByRole('button', { name: 'Review Wikibooks test rice', exact: true }).click();
    await page.getByRole('dialog', { name: 'Review imported recipe', exact: true }).waitFor();
    check(await page.getByLabel('Ingredient 1 quantity').inputValue(), '2', 'Wikibooks explicit quantity converts');
    check(await page.getByLabel('Ingredient 2 quantity').inputValue(), '', 'Wikibooks uncertain quantity needs review');
    check(await modal.getByRole('link', { name: 'CC BY-SA 4.0', exact: true }).isVisible(), true, 'Licence is visible before import');
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      check(await modal.evaluate(el => el.scrollWidth <= el.clientWidth), true, `Wikibooks review fits ${width}px`);
    }
    await page.getByLabel('Minutes', { exact: true }).fill('20');
    await page.getByLabel('Servings', { exact: true }).fill('4');
    await page.getByLabel('Ingredient 2 name').fill('salt');
    await page.getByLabel('Ingredient 2 quantity').fill('0.25');
    await page.getByLabel('Ingredient 2 unit').selectOption('tsp');
    await page.getByRole('button', { name: 'Add to my cookbook ↗', exact: true }).click();
    await modal.getByRole('heading', { name: wikiPage.title, exact: true }).waitFor();
    const wikiSaved = (await (await request.get('/api/recipes')).json()).find(r => r.wikibooks_id === wikiPage.page_id);
    check(wikiSaved.wikibooks_revision, wikiPage.revision, 'Saved recipe retains original revision');
    const duplicateResponse = await request.post('/api/recipes', { data: { ...wikiSaved, prevent_duplicate: true } });
    check(duplicateResponse.status(), 409, 'Backend prevents reimporting the same source recipe');
    const textDownloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download recipe', exact: true }).click();
    const textDownload = await textDownloadPromise;
    const wikiText = fs.readFileSync(await textDownload.path(), 'utf8');
    check(wikiText.includes('CC BY-SA 4.0') && wikiText.includes('oldid=987654'), true, 'Readable download retains source credit and licence');
    const jsonDownloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export recipe file', exact: true }).click();
    const wikiExport = JSON.parse(fs.readFileSync(await (await jsonDownloadPromise).path(), 'utf8')).recipes[0];
    check(wikiExport.licence, 'CC BY-SA 4.0', 'Portable export includes licence');
    check(wikiExport.attribution.includes('Contributor history'), true, 'Portable export includes contributor attribution');
    await page.getByRole('button', { name: 'Decrease servings', exact: true }).click();
    await page.getByRole('button', { name: 'Decrease servings', exact: true }).click();
    const wikiDay = await page.locator('#plan-day').inputValue();
    await page.getByRole('button', { name: 'Add to meal plan ↗', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Dinner is on the menu.');
    const wikiItems = await (await request.get(`/api/shopping?start=${wikiDay}&end=${wikiDay}`)).json();
    check(wikiItems.find(i => i.name === 'rice').quantity, 1, 'Wikibooks recipe integrates with shopping scaling');
    await page.keyboard.press('Escape');
    await modal.waitFor({ state: 'detached' });
    check(await page.getByRole('button', { name: 'Open saved Wikibooks test rice', exact: true }).isVisible(), true, 'Saved result opens existing recipe');
    await page.getByRole('button', { name: 'Open saved Wikibooks test rice', exact: true }).click();
    await modal.getByRole('heading', { name: wikiPage.title, exact: true }).waitFor();
    await page.getByRole('button', { name: 'Edit recipe', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).fill('My community rice');
    await page.getByRole('button', { name: 'Save changes ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'My community rice', exact: true }).waitFor();
    check(await modal.getByRole('link', { name: 'Wikibooks contributors — view original', exact: true }).getAttribute('href'), 'https://en.wikibooks.org/w/index.php?oldid=987654', 'Recipe edits preserve attribution');
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Open My community rice', exact: true }).click();
    check(await modal.getByRole('link', { name: 'CC BY-SA 4.0', exact: true }).isVisible(), true, 'Licence persists after reload');
    await page.keyboard.press('Escape');
    await modal.waitFor({ state: 'detached' });
    await request.delete(`/api/recipes/${wikiSaved.id}`);
    await page.unroute('**/api/discover**');
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.route('https://www.thecocktaildb.com/images/**', route => route.fulfill({ contentType: 'image/svg+xml', body: fs.readFileSync('recipe-app/public/art/drinks.svg', 'utf8') }));
    await page.getByRole('button', { name: 'Drinks', exact: true }).click();
    await page.getByRole('heading', { name: 'Something good to sip.', exact: true }).waitFor();
    await page.getByLabel('Drink type', { exact: true }).selectOption('non-alcoholic');
    await page.getByRole('button', { name: 'Search drinks', exact: true }).click();
    await page.getByRole('button', { name: 'Preview Afterglow', exact: true }).waitFor();
    check(await page.locator('.recipe-card').count(), 1, 'Non-alcoholic browse');
    check(await page.getByRole('button', { name: 'Surprise me with a drink', exact: true }).count(), 0, 'Filtered browse has no unrestricted random');
    await page.getByRole('button', { name: 'Preview Afterglow', exact: true }).click();
    const drinkModal = page.getByRole('dialog');
    await drinkModal.getByText('4 oz', { exact: true }).waitFor();
    checks++;
    check(await drinkModal.getByText('Mix with ice and serve.', { exact: true }).isVisible(), true, 'Filter summaries fetch full method');
    await page.screenshot({ path: 'test-results/drink-preview.png', fullPage: true });
    await page.getByRole('button', { name: '♡ Save drink', exact: true }).click();
    await drinkModal.getByText('♥ In your saved drinks', { exact: true }).waitFor();
    checks++;
    const downloadDrinkPromise = page.waitForEvent('download');
    await drinkModal.getByRole('button', { name: 'Download drink', exact: true }).click();
    const drinkDownload = await downloadDrinkPromise;
    const drinkText = fs.readFileSync(await drinkDownload.path(), 'utf8');
    check(drinkText.includes('4 oz — Orange juice') && drinkText.includes('TheCocktailDB'), true, 'Drink download retains measures and source');
    await page.keyboard.press('Escape'); await drinkModal.waitFor({ state: 'detached' });
    await page.reload(); await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Drinks', exact: true }).click();
    await page.getByRole('button', { name: 'Saved drinks (1)', exact: true }).click();
    await page.getByRole('button', { name: 'Open saved drink Afterglow', exact: true }).waitFor();
    check((await request.get('/api/drinks')).ok(), true, 'Saved drinks API available');
    const persistedDrinks = await (await request.get('/api/drinks')).json();
    check(persistedDrinks.length, 1, 'Saved drink persists in SQLite');
    const duplicateDrink = await request.post('/api/drinks', { data: { cocktaildb_id: '12560' } });
    check(duplicateDrink.status(), 200, 'Duplicate saves open the existing record');
    await page.getByRole('button', { name: 'Open saved drink Afterglow', exact: true }).click();
    await drinkModal.waitFor();
    await drinkModal.getByRole('button', { name: 'Remove saved drink', exact: true }).click();
    await drinkModal.getByRole('button', { name: 'Keep drink', exact: true }).click();
    check(await drinkModal.getByRole('button', { name: 'Yes, remove drink', exact: true }).count(), 0, 'Cancelled removal preserves drink');
    await drinkModal.getByRole('button', { name: 'Remove saved drink', exact: true }).click();
    await drinkModal.getByRole('button', { name: 'Yes, remove drink', exact: true }).click();
    await drinkModal.waitFor({ state: 'detached' });
    check((await (await request.get('/api/drinks')).json()).length, 0, 'Confirmed removal persists');
    await page.getByRole('button', { name: 'Find drinks', exact: true }).click();
    await page.getByRole('button', { name: 'Surprise me with a drink', exact: true }).click();
    await page.getByRole('button', { name: 'Preview Margarita', exact: true }).waitFor();
    checks++;
    await page.screenshot({ path: 'test-results/drinks-desktop.png', fullPage: true });
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Drinks page fits ${width}px`);
      await page.getByRole('button', { name: 'Preview Margarita', exact: true }).click();
      await drinkModal.waitFor();
      check(await drinkModal.getByText('Amount not specified', { exact: true }).isVisible(), true, 'Missing measures remain explicit');
      check(await drinkModal.evaluate(node => node.scrollWidth <= node.clientWidth), true, `Drink preview fits ${width}px`);
      if (width === 390) await page.screenshot({ path: 'test-results/drinks-mobile.png', fullPage: true });
      await page.keyboard.press('Escape'); await drinkModal.waitFor({ state: 'detached' });
    }
    await page.route('**/api/drinks/discover**', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Drink provider offline."}' }));
    await page.getByRole('button', { name: 'Surprise me with a drink', exact: true }).click();
    await page.getByRole('alert').filter({ hasText: 'Drink provider offline.' }).waitFor();
    checks++;
    await page.unroute('**/api/drinks/discover**');
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.route('**/api/recipes', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Test kitchen unavailable."}' }));
    await page.reload();
    await page.getByRole('alert').filter({ hasText: 'Test kitchen unavailable.' }).waitFor();
    checks++;
    await page.unroute('**/api/recipes');
    await page.getByRole('button', { name: 'Try again', exact: true }).click();
    await page.locator('.recipe-card').first().waitFor();
    check(await page.locator('.recipe-card').count(), 8, 'Retry after server error');
    check(errors, [], 'No browser exceptions');
    console.log(`PASS: ${checks} browser checks across cookbook CRUD, planning, shopping, persistence, and mobile layouts.`);
  } catch (error) {
    fs.mkdirSync('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/failure.png', fullPage: true }).catch(() => {});
    throw error;
  } finally { await request.dispose(); await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
