const assert = require('node:assert/strict');
const fs = require('node:fs');
let playwright;
try { playwright = require('playwright'); } catch { playwright = require(`${process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES}/playwright`); }
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5000';
(async () => {
  const browser = await playwright.chromium.launch({ headless: true });
  let checks = 0;
  const check = (actual, expected, label) => { assert.deepEqual(actual, expected, label); checks++; };
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const request = await playwright.request.newContext({ baseURL: base });
  try {
    await page.goto(base);
    await page.locator('.recipe-card').first().waitFor();
    check(await page.locator('.recipe-card').count(), 8, 'Seeded recipes render');
    await page.getByRole('button', { name: 'Open Spaghetti Bolognese', exact: true }).click();
    const modal = page.getByRole('dialog');
    check(await modal.getByRole('heading', { name: 'Spaghetti Bolognese' }).isVisible(), true, 'Detail view');
    await page.getByRole('button', { name: 'Increase servings' }).click();
    check(await page.getByTestId('servings').textContent(), '5 servings', 'Serving adjustment');
    check(await page.getByTestId('ingredient-quantity').first().textContent(), '500 g', 'Ingredients scale');
    await page.getByRole('button', { name: 'Mark step 1 complete' }).click();
    check(await page.getByRole('button', { name: 'Mark step 1 incomplete' }).getAttribute('aria-pressed'), 'true', 'Cooking checklist');
    await page.getByRole('button', { name: '♡ Save recipe', exact: true }).click();
    await page.getByRole('button', { name: '♥ Saved', exact: true }).waitFor();
    checks++;
    await page.keyboard.press('Escape');
    await page.getByRole('dialog').waitFor({ state: 'detached' });
    checks++;
    await page.getByRole('button', { name: 'Saved recipes', exact: true }).click();
    check(await page.locator('.recipe-card').count(), 3, 'Saved recipes');
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('coconut milk');
    check(await page.locator('.recipe-card').count(), 1, 'Ingredient search');
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('unfindable');
    check(await page.getByText('No recipes on this shelf.').isVisible(), true, 'Empty search');
    await page.getByRole('textbox', { name: 'Search recipes' }).fill('');
    await page.getByRole('button', { name: 'Desserts', exact: true }).click();
    check(await page.locator('.recipe-card').count(), 1, 'Category filter');
    await page.getByRole('button', { name: 'All recipes', exact: true }).click();
    await page.getByRole('button', { name: '＋ Add recipe', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).fill('Browser test rice');
    await page.getByLabel('What makes it special?').fill('A test recipe for an actual weekly shopping list.');
    await page.getByLabel('Minutes', { exact: true }).fill('15');
    await page.getByLabel('Servings', { exact: true }).fill('2');
    await page.getByLabel('Ingredient 1 name').fill('rice');
    await page.getByLabel('Ingredient 1 quantity').fill('100');
    await page.getByLabel('Step 1', { exact: true }).fill('Cook the rice according to the packet.');
    await page.getByRole('button', { name: 'Add to my cookbook ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'Browser test rice', exact: true }).waitFor();
    checks++;
    await page.getByRole('button', { name: 'Edit recipe', exact: true }).click();
    await page.getByLabel('Recipe name', { exact: true }).fill('Everyday rice');
    await page.getByRole('button', { name: 'Save changes ↗', exact: true }).click();
    await modal.getByRole('heading', { name: 'Everyday rice', exact: true }).waitFor();
    checks++;
    await page.getByRole('button', { name: 'Increase servings' }).click();
    const day = await page.locator('#plan-day').inputValue();
    await page.getByRole('button', { name: 'Add to meal plan ↗', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Dinner is on the menu.');
    checks++;
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
    const slot = page.locator(`[id="${day}-Dinner"]`);
    check(await slot.locator('option:checked').textContent(), 'Everyday rice', 'Meal appears on selected day');
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.locator('.shopping-item').first().waitFor();
    check(await page.locator('.shopping-item').count(), 1, 'Shopping list generated');
    check(await page.locator('.shopping-item').textContent(), 'rice150 g', 'Shopping quantities use planned servings');
    await page.locator('.shopping-item input').check();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'One less thing to pick up.');
    await page.reload();
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.locator('.shopping-item').first().waitFor();
    check(await page.locator('.shopping-item input').isChecked(), true, 'Shopping checks persist');
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download my list ↓', exact: true }).click();
    const download = await downloadPromise;
    check(download.suggestedFilename().startsWith('shopping-'), true, 'Shopping list export');
    const path = await download.path();
    check(fs.readFileSync(path, 'utf8').includes('[x] rice: 150 g'), true, 'Export contains real list data');
    await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
    await page.getByRole('button', { name: 'Next week', exact: true }).click();
    await page.getByRole('button', { name: 'Shopping list', exact: true }).click();
    await page.getByText('Your basket starts with a plan.').waitFor();
    checks++;
    await page.getByRole('button', { name: 'This week', exact: true }).click();
    await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    await page.getByRole('button', { name: 'Open Everyday rice', exact: true }).click();
    await page.getByRole('button', { name: 'Delete recipe', exact: true }).click();
    await page.getByRole('button', { name: 'Keep it', exact: true }).click();
    check(await modal.isVisible(), true, 'Delete cancellation');
    await page.getByRole('button', { name: 'Delete recipe', exact: true }).click();
    await page.getByRole('button', { name: 'Yes, delete recipe', exact: true }).click();
    await modal.waitFor({ state: 'detached' });
    check(await page.locator('.recipe-card').count(), 8, 'Delete recipe');
    const plan = await (await request.get('/api/plan')).json();
    check(plan, [], 'Deletion removes planned meals');
    await page.reload();
    await page.locator('.recipe-card').first().waitFor();
    await page.getByRole('button', { name: 'Unsave Spaghetti Bolognese', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.toast').textContent === 'Recipe removed from saved.');
    fs.mkdirSync('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/cookbook-desktop.png', fullPage: true });
    for (const width of [320, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 844 });
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Cookbook fits ${width}px`);
      if (width === 390) await page.screenshot({ path: 'test-results/cookbook-mobile.png', fullPage: true });
      await page.getByRole('button', { name: 'Open Spaghetti Bolognese', exact: true }).click();
      check(await modal.evaluate(el => el.scrollWidth <= el.clientWidth), true, `Recipe detail fits ${width}px`);
      await page.keyboard.press('Escape');
      await modal.waitFor({ state: 'detached' });
      await page.getByRole('button', { name: 'Meal planner', exact: true }).click();
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Meal plan fits ${width}px`);
      await page.getByRole('button', { name: 'Recipes', exact: true }).click();
    }
    await page.locator('.recipe-card').last().scrollIntoViewIfNeeded();
    await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
    checks++;
    await page.route('**/api/recipes', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Test kitchen unavailable."}' }));
    await page.reload();
    await page.getByRole('alert').filter({ hasText: 'Test kitchen unavailable.' }).waitFor();
    checks++;
    await page.unroute('**/api/recipes');
    await page.getByRole('button', { name: 'Try again', exact: true }).click();
    await page.locator('.recipe-card').first().waitFor();
    check(await page.locator('.recipe-card').count(), 8, 'Retry after server error');
    check(errors, [], 'No browser exceptions');
    console.log(`PASS: ${checks} browser checks across cookbook CRUD, planning, shopping, persistence, and mobile layouts.`);
  } catch (error) {
    fs.mkdirSync('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/failure.png', fullPage: true }).catch(() => {});
    throw error;
  } finally { await request.dispose(); await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
