import React, { useState } from 'react';
import KitchenTools from './KitchenTools';
import { artURL, quantity, localDay } from './api';

export default function RecipeDetail({ recipe, onFavorite, onEdit, onDelete, onPlan, onJournal, onCooked, onDuplicate, busy }) {
  const [servings, setServings] = useState(recipe.servings);
  const [cooked, setCooked] = useState([]);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [day, setDay] = useState(localDay(new Date()));
  const [slot, setSlot] = useState('Dinner');
  const ratio = servings / recipe.servings;
  return <div className="recipe-detail"><div className="detail-top"><img src={artURL(recipe)} alt={`Illustration of ${recipe.title}`} /><div><span className="eyebrow">{recipe.category} · {recipe.time} MINUTES</span><h2>{recipe.title}</h2><p>{recipe.description}</p><div className="detail-buttons"><button className="button" disabled={busy} aria-pressed={recipe.favorite} onClick={() => onFavorite(recipe)}>{recipe.favorite ? '♥ Saved' : '♡ Save recipe'}</button><button className="button" disabled={busy} onClick={() => onEdit(recipe)}>Edit recipe</button></div></div></div>
    <div className="detail-body"><section><div className="ingredient-heading"><h3>Ingredients</h3><div className="servings"><button aria-label="Decrease servings" disabled={servings <= 1} onClick={() => setServings(s => s - 1)}>−</button><span data-testid="servings">{servings} servings</span><button aria-label="Increase servings" disabled={servings >= 24} onClick={() => setServings(s => s + 1)}>＋</button></div></div><ul className="ingredients">{recipe.ingredients.map((ingredient, index) => <li key={index}><span>{ingredient.name}</span><strong data-testid="ingredient-quantity">{quantity(ingredient.quantity * ratio)} {ingredient.unit}</strong></li>)}</ul><p className="muted tiny">Quantities scale with servings. Cooking times and written instructions stay as written; adjust the pan size and cook in batches when needed.</p><div className="plan-recipe"><h3>A place at your table</h3><label htmlFor="plan-day">Date</label><input type="date" id="plan-day" required value={day} onChange={e => setDay(e.target.value)} /><label htmlFor="plan-slot">Meal</label><select id="plan-slot" value={slot} onChange={e => setSlot(e.target.value)}>{['Breakfast', 'Lunch', 'Dinner'].map(s => <option key={s}>{s}</option>)}</select><button className="button primary full" disabled={busy || !day} onClick={() => onPlan(recipe.id, day, slot, servings)}>Add to meal plan ↗</button></div></section><section><h3>Let’s make it</h3><p className="muted tiny">Tap each step as you go. Progress lasts while this recipe stays open.</p><ol className="steps">{recipe.instructions.map((instruction, index) => <li className={cooked.includes(index) ? 'done' : ''} key={index}><button aria-label={`Mark step ${index + 1} ${cooked.includes(index) ? 'incomplete' : 'complete'}`} aria-pressed={cooked.includes(index)} onClick={() => setCooked(old => old.includes(index) ? old.filter(i => i !== index) : [...old, index])}>{cooked.includes(index) ? '✓' : String(index + 1).padStart(2, '0')}</button><p>{instruction}</p></li>)}</ol><KitchenTools recipe={recipe} servings={servings} busy={busy} onJournal={onJournal} onCooked={onCooked} onDuplicate={onDuplicate} /><div className="delete-recipe">{confirmDelete ? <><p>Delete this recipe and remove it from your meal plan?</p><button className="button danger" disabled={busy} onClick={() => onDelete(recipe)}>Yes, delete recipe</button><button className="text-button" onClick={() => setConfirmDelete(false)}>Keep it</button></> : <button className="text-button" disabled={busy} onClick={() => setConfirmDelete(true)}>Delete recipe</button>}</div></section></div>
  </div>;
}
